version: '3.8'

services:
  wallet-db:
    image: postgres:alpine
    container_name: wallet-db
    env_file:
      - .env
    volumes:
      - /home/vladislav/mydirs/project/solutions/db/wallet_tg_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: suser
      POSTGRES_USER: pikakip
      POSTGRES_DB: wallet
    ports:
      - "5555:5432"

  wallet-bot:
    build: .
    container_name: wallet-bot
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - wallet-db

volumes:
  wallet-data:
